### PR TITLE
[Dependencies] Upgrade nock

### PR DESCRIPTION
**Pull request by k0nserv**
This resolves the build errors. I also added `package-lock.json` to ensure deterministic builds

### CODE REVIEW

**Comment by athieriot** [comment]
Wow that was quick

Nice one ! Thanks.

**Comment by k0nserv** [comment]
Still fails though :(

**Comment by tboerger** [comment]
coverage and publish will anyway always fail... coverage is dead and publish is missing all secrets.

**Comment by athieriot** [comment]
Damn. I've been away for a long time it seems

**Comment by k0nserv** [comment]
Strange that `make test` works well locally though

**Comment by k0nserv** [comment]
Upgraded to node lts for the build step which resolved that issue. @athieriot I assume both the coverage and publish steps will fail on master though?

**Comment by athieriot** [comment]
I'll see what I can do about that.

If I don't find the time to fix it properly I can still push the image
manually for now

**Comment by k0nserv** [comment]
That'd be awesome thanks :)

**Pull request merged**
