### PR TITLE
Add support for Drone 0.5

### PR DESCRIPTION
**Pull request by jmccann**
Update plugin to work with Drone 0.5.  Should also continue to work with Drone 0.4.

DOCS.md reflects Drone 0.5 usage pattern.

### CODE REVIEW

**Comment by athieriot** [comment]
That's brilliant. Thank you.

Is the README.md still valid?

I'm going to have to check if I can still build the Docker Image automatically but your PR is perfect

**Comment by jmccann** [comment]
`README.md` is valid for 0.4.  In 0.5 though args are passed through ENVVARs now so it's obsolete.

You may want to clean it up yourself though as badges may need to be updated/removed also now that you are owner.

Thanks!

**Comment by athieriot** [comment]
lgtm?

**Comment by athieriot** [comment]
lgtm

**Comment by athieriot** [comment]
lgtm

**Comment by athieriot** [comment]
LGTM

**Comment by athieriot** [comment]
OK. Sorry for the millions of notifications you must have received but I was trying to understand what was happening :)

I removed LGTM as you suggested in favour of Github reviews and setup the proper Docker image at https://hub.docker.com/r/athieriot/drone-artifactory/

I only miss the code coverage display but that shouldn't be a show stopper.

Thank you again for this awesome Pull Request and I'll be glad to accept more if you find a problem from now on :)

**Pull request merged**
